services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env_db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

  bot:
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db:
